- Himanshu Sharma(IT 2nd yr.).txt
> Adding Intro

- Sanya Barnwal (IT, 2nd Year)
>  Sanya Barnwal (IT, 2nd Year)

- Sumit Shukla IT 2nd Year.txt
> Adding txt file

- Sumit Shukla IT 2nd Year.txt
I  have updated the Introduction
> Updated the Introduction

- Aditya Pandey (CSE).txt
I have added my name, branch and year in the repo.
> Aditya Pandey (CSE)

- anamika-mishra.txt
> Anamika Mishra (EE)

- PranjaliIT2nd.txt
> pranjali ,IT,2ND

- AnushkaSingh.txt
> AnushkaSinghCHE(2nd year)

- Muskan Sharma(CSE 2nd year).txt
> Muskan Sharma

- naicyIT2ndyear.txt
> naincyIT2nd year

- Nilesh Kumar.txt
- Nilesh.txt
> Nilesh Kumar (IT)

- Sarthak kesarwani CSE.txt
Name: Sarthak Kesarwani 
Branch: CSE
Year: 2nd
> Sarthak Kesarwani CSE - Day1

- garimatyagiIT2ndyear.txt
> Garima Tyagi

- Deepak kasaudhan CSE.txt
> Deepak kasaudhan CSE - Day1

- Archanacse2ndyear.txt
> Archana (cse) 2nd year

- janhavimauryaIT2ndyear.txt
> Janhavi Maurya 2ndyear(IT)

- tejashwaniEE2ndyr.txt
> initial commit

- Shreyam_Pandey_CSE.txt
> Add Shreyam_Pandey_CSE.txt

- SwatiCE2ndyear.txt
> Swati CE (2nd year)

- AnuskaIT2ndyear.txt
> Anushka IT2nd year
